name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  packages:
    name: Build
    uses: ./.github/workflows/packages.yml
    with:
      release-repo: github:${{ github.repository }}
